// auto-generated by bsg_ascii_to_rom.py from /homes/shx089/bsg_manycore/software/spmd/bsg_BSX_loopback/main.bin; do not modify
module bsg_manycore_io_complex_rom #(parameter width_p=-1, addr_width_p=-1)
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
         0: data_o = width_p ' (32'b11010000000011011111010100110111); // 0xD00DF537
         1: data_o = width_p ' (32'b10101101000001010000010100010011); // 0xAD050513
         2: data_o = width_p ' (32'b00000000000001010010000000100011); // 0x00052023
         3: data_o = width_p ' (32'b00000000000000000000000001101111); // 0x0000006F
   default: data_o = { width_p { 1'b0 } };
endcase
endmodule
