##################################################################################
#      some parameters get from the manycore program and pass it to the VCS
#      this file should be included in Makefile
manycore_cfg_file= $(benchmark_dir)/$(BENCHMARK)/manycore.cfg.h
manycore_pkg_file= $(BSG_DESIGNS_TARGET_DIR)/v/bsg_manycore_pkg.v

# The number of tiles
bsg_tiles_X			?= 16 
bsg_tiles_Y			?= 31

############################################################
# The rocc configuration
# The number of rocc interface
bsg_rocc_num 		?= 4

# The index vector of all rocc interfaces.
# starting from 1, Each no zero hex value indicates a rocc interface in the X axis
#                      "x15 x14 x13 ....     x1 x0"
bsg_rocc_dist_vec	?= "64'h0400_0300_0200_0100"
#                            x14  x10  x6  x2

############################################################
# Do we test the dcdc manycore ? 
bsg_enable_dcdc  	?= 0
bsg_enable_trace  	?= 0
bsg_enable_replay  	?= 0

ifneq "$(bsg_enable_trace)" "0"
bsg_enable_replay = 0
endif


# The active rocc interface index, starting from zero
# The value must be one of the indices of the "No zero hex" in bsg_rocc_dist_vec
bsg_manycore_rocket_index  ?=0

ifeq "$(bsg_manycore_rocket_index)" "0"
bsg_active_rocc_index = 0
else ifeq "$(bsg_manycore_rocket_index)" "1"
bsg_active_rocc_index = 4
else ifeq "$(bsg_manycore_rocket_index)" "2"
bsg_active_rocc_index = 10
else
bsg_active_rocc_index = 14
endif

############################################################
# The out fifo configuration
bsg_out_fifo_num 	  ?= 4
bsg_out_fifo_dist_vec ?="64'h0004_0003_0002_0001"
#						      x12   x8   x4   x0
# used for rocket c program only 
OUT_FIFO_DIST 		  ?='{3,7,8,12}'

##########
# Pass the parameters to VCS through macro definition
VCS_OPT += +define+bsg_tiles_X=$(bsg_tiles_X)
VCS_OPT += +define+bsg_tiles_Y=$(bsg_tiles_Y)
VCS_OPT += +define+bsg_rocc_num=$(bsg_rocc_num)
VCS_OPT += +define+bsg_rocc_dist_vec=$(bsg_rocc_dist_vec)
#VCS_OPT += +define+bsg_active_fsb_index=$(bsg_active_fsb_index)

VCS_OPT += +define+bsg_out_fifo_num=$(bsg_out_fifo_num)
VCS_OPT += +define+bsg_out_fifo_dist_vec=$(bsg_out_fifo_dist_vec)

ifneq "$(bsg_enable_dcdc)" "0"
VCS_OPT += +define+bsg_enable_dcdc
endif

ifneq "$(bsg_enable_trace)" "0"
VCS_OPT += +define+bsg_enable_trace
endif

ifneq "$(bsg_enable_replay)" "0"
VCS_OPT += +define+bsg_enable_replay
endif


